#!/bin/bash
echo "🏗️  ARQUITETURA ZENNITH - VISÃO GERAL"
echo "====================================="

echo ""
echo "🎯 CAMADAS DO SISTEMA:"
echo ""
echo "📚 CAMADA CORE (utils_zennith_*):"
echo "   • utils_zennith_log_avancado.sh - Sistema corporativo de logging"
echo "   • utils_zennith_processamento.sh - Biblioteca de processamento"
echo ""
echo "🔧 CAMADA DE APLICAÇÃO:"
echo "   • Scripts principais otimizados"
echo "   • Funções especializadas"
echo "   • Código modular e reutilizável"
echo ""
echo "📊 CAMADA DE DADOS:"
echo "   • Documentação organizada"
echo "   • Logs estruturados"
echo "   • Configurações centralizadas"
echo ""
echo "🔄 PRINCÍPIOS ARQUITETURAIS:"
echo "   • Separação de responsabilidades"
echo "   • Baixo acoplamento, alta coesão"
echo "   • Reutilização máxima"
echo "   • Manutenibilidade otimizada"
