#!/bin/bash
# Script de autenticação direta com GitHub
echo "🔑 MÉTODOS DE AUTENTICAÇÃO DISPONÍVEIS:"
echo "1. GitHub CLI (gh auth login)"
echo "2. PAT direto na URL"
echo "3. Configuração manual de credenciais"
echo ""
echo "🎯 RECOMENDADO: Método 2 - PAT direto"
echo ""
echo "📝 INSTRUÇÕES PARA PAT:"
echo "1. Vá para: https://github.com/settings/tokens"
echo "2. Clique em 'Generate new token'"
echo "3. Nomeie: 'FUNDAÇÃO ALQUIMISTA SYNCH'"
echo "4. Expiração: 90 dias"
echo "5. Permissões: SELECIONE 'repo' E 'workflow'"
echo "6. Clique em 'Generate token'"
echo "7. COPIE o token gerado"
echo ""
echo "🚀 COMANDO FINAL:"
echo "git push https://[SEU_TOKEN_AQUI]@github.com/DanielToloczkoCoutinho/fundacao-alquimista-anatheron.git main"
