#!/bin/bash

echo "🔧 CONFIGURAÇÃO DE SECRETS PARA GITHUB ACTIONS"
echo "=============================================="

echo "📋 PASSO A PASSO PARA CONFIGURAR:"
echo ""
echo "1. 🌐 Acesse: https://github.com/DanielToloczkoCoutinho/fundacao-alquimista-anatheron/settings/secrets/actions"
echo ""
echo "2. 🔑 Adicione estas variáveis:"
echo "   - Nome: VERCEL_TOKEN"
echo "   - Valor: [Seu token Vercel - vá em vercel.com/account/tokens]"
echo ""
echo "   - Nome: VERCEL_ORG_ID"  
echo "   - Valor: [Team ID - vá em vercel.com/account/[sua-organizacao]]"
echo ""
echo "   - Nome: VERCEL_PROJECT_ID"
echo "   - Valor: [Project ID - vá no projeto no Vercel > Settings > General]"
echo ""
echo "3. 💾 Salve e PRONTO!"
echo "4. 🚀 O GitHub Actions fará deploy automático em cada push!"
echo ""
echo "🎯 SEU TOKEN VERCEL ATUAL:"
echo "   T8xoTgqDdeXf78lVq5teuVal"
echo ""
echo "⚠️  Se esse token não funcionar, gere um novo em:"
echo "   https://vercel.com/account/tokens"
